name: Probando custom actions
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3

      - name: Probando timeout
        run: sleep 120

      - name:  Probando actions
        id: foo
        uses: Sgomez04/hello-world-composite-action@main
        with:
          who-to-greet: 'Sebas'

      - name: Mostrar numero aleatorio obtenido de la action
        run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  comando_hola:
    runs-on: ubuntu-latest
    steps:
      - name: simple
        run: echo "hola"