name: Probando custom actions
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: Sgomez04/hello-world-composite-action@main
        with:
          who-to-greet: 'Sebas'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
